import { SkillIds } from "@/components/pages/skills/lib/skill.constants";

export const skillNames = new Map<SkillIds, string>()
  .set(SkillIds.html, "HTML")
  .set(SkillIds.css, "CSS")
  .set(SkillIds.js, "Java Script")
  .set(SkillIds.ts, "Type Script")
  .set(SkillIds.react, "React.js")
  .set(SkillIds.reactNative, "React Native")
  .set(SkillIds.next, "Next.js")
  .set(SkillIds.redux, "Redux")
  .set(SkillIds.reduxForm, "Redux Form")
  .set(SkillIds.formik, "Formik")
  .set(SkillIds.reduxToolkit, "Redux Toolkit")
  .set(SkillIds.mobx, "MobX")
  .set(SkillIds.zustand, "Zustand")
  .set(SkillIds.echarts, "Apache Echarts")
  .set(SkillIds.i18, "i18-next")
  .set(SkillIds.reactQuery, "React Query")
  .set(SkillIds.reactHookForm, "React Hook Form")
  .set(SkillIds.axios, "axios")
  .set(SkillIds.shadcn, "shadcn/ui")
  .set(SkillIds.mui, "Material UI")
  .set(SkillIds.sc, "Styled Components")
  .set(SkillIds.tailwind, "Tailwind CSS")
  .set(SkillIds.bootstrap, "Bootstrap")
  .set(SkillIds.sass, "SCSS")
  .set(SkillIds.github, "GitHub")
  .set(SkillIds.gitlab, "GitLab")
  .set(SkillIds.jira, "Jira")
  .set(SkillIds.jwt, "JWT")
  .set(SkillIds.node, "Node.js (Express)")
  .set(SkillIds.googleMapsApi, "Google Maps API")
  .set(SkillIds.sequelize, "Sequelize")
  .set(SkillIds.prisma, "Prisma")
  .set(SkillIds.mysql, "MySQL")
  .set(SkillIds.postgre, "Postgre SQL")
  .set(SkillIds.mongodb, "MongoDB")
  .set(SkillIds.mongoose, "Mongoose")
  .set(SkillIds.handlebars, "Handlebars")
  .set(SkillIds.vite, "Vite")
  .set(SkillIds.webpack, "Webpack");
